docs: update the doc of slow subs
emqtt/emq-docs-cn pull request #1012
Opened 2022-02-09 03:31 UTC by lafirest

2022-02-09 17:44 UTC, zmstone commented on en_US/modules/slow_subscribers_statistics.md
> +This function will track the time consumption of the entire message transmission process after the QoS1 and QoS2 messages arrive at EMQX, and then calculate the message transmission latency according
With this feature enabled, EMQ X will start measuring message transmission latency. The measurement always starts at when a message is received by EMQ X, the end of the measurement is configurable. See more details….

2022-02-09 17:45 UTC, zmstone commented on en_US/modules/slow_subscribers_statistics.md
> +Afterwards, the subscribers and topics are ranked according to the latency.
```suggestion
The per clientid-topic latency measurements are then ranked in the table view.
```

2022-02-09 17:50 UTC, zmstone commented on en_US/modules/slow_subscribers_statistics.md
> +    *threshold* is used to determine whether subscribers can participate in statistics. If the latency of subscribers is lower than this value, they will not be counted
```suggestion
    *threshold* is the minimum number of milliseconds the latency has to exceed, otherwise not collected for ranking 
```

2022-02-09 17:51 UTC, zmstone commented on en_US/modules/slow_subscribers_statistics.md
> +    This field determines the upper limit of the number in the statistical record table
```suggestion
    This field determines the upper limit of the number of statistical records in the ranking table
```

2022-02-09 17:59 UTC, zmstone commented on en_US/modules/slow_subscribers_statistics.md
> +	*expire interval* controls the effective time of each piece of data in the statistical record. If the data has not been updated within this time range, it will be removed. (For example, after a mess
```suggestion
	*expire interval* controls the effective time of each ranking record. If the a client-topic has no higher latency inserted for such long time, the record expires. For example if expire interval is 5 minutes, and client1-topic1 had a latency 500ms recorded (ranked top-K) at T1, and for the next 5 minutes, if there is no further measurements greater than 500, the ranking recorded will be deleted shortly after T1+5min
```

2022-02-11 08:01 UTC, HJianBo requested changes

2022-02-11 08:01 UTC, hjianbo commented on zh_CN/modules/slow_subscribers_statistics.md
> +![image](./assets/slow_subscribers_statistics_2.png)
Text is better. And the picture here is cut off too much.

2022-02-15 14:46 UTC, zmstone approved these changes, later dismissed

2022-02-17 06:19 UTC, HJianBo approved these changes

2022-02-17 06:35 UTC, merged