fix(v4.4): merge emqx broker and enterprise docs
emqtt/emq-docs-cn pull request #1014
Opened 2022-02-10 09:26 UTC by Swilder-M

2022-02-10 10:19 UTC, zmstone approved these changes, later dismissed

2022-02-11 01:37 UTC, wivwiv requested changes

2022-02-11 01:37 UTC, wivwiv commented on zh_CN/getting-started/install-ee.md
> +## Windows
企业版没有 windows 版本相关内容了

2022-02-11 01:37 UTC, wivwiv commented on zh_CN/modules/http_authentication.md
> + - 认证失败：API 返回 4xx 状态码
此处应该用修改前的内容

2022-02-11 01:37 UTC, wivwiv commented on zh_CN/getting-started/install-ee.md
> -  - CentOS8.X
保留左边的内容

2022-02-15 07:42 UTC, tigercl approved these changes

2022-02-15 07:43 UTC, merged