Sync release 4.3
emqtt/emq-docs-cn pull request #1150
Opened 2022-05-20 09:53 UTC by tigercl

2022-05-23 08:13 UTC, zmstone commented on en_US/getting-started/install-on-k8s.md
> +      image: emqx/emqx:4.3.11
4.4 ?

2022-05-23 08:14 UTC, zmstone commented on en_US/getting-started/install-on-k8s.md
> +    Node 'emqx@emqx-0.emqx-headless.default.svc.cluster.local' 4.3.11 is started
4.4

2022-05-23 08:14 UTC, zmstone commented on en_US/getting-started/install-on-k8s.md
> +      image: emqx/emqx-ee:4.3.6
4.4

2022-05-23 08:14 UTC, zmstone commented on en_US/getting-started/install-on-k8s.md
> +   Node 'emqx-ee@emqx-ee-0.emqx-ee-headless.default.svc.cluster.local' 4.3.6 is started
4.4

2022-05-23 08:14 UTC, zmstone commented on zh_CN/getting-started/install-on-k8s.md
> +      image: emqx/emqx:4.3.11
4.4

2022-05-23 08:14 UTC, zmstone commented on zh_CN/getting-started/install-on-k8s.md
> +      image: emqx/emqx-ee:4.3.6
4.4

2022-05-23 08:14 UTC, zmstone commented on zh_CN/getting-started/install-on-k8s.md
> +   Node 'emqx-ee@emqx-ee-0.emqx-ee-headless.default.svc.cluster.local' 4.3.6 is started
4.4

2022-05-24 09:16 UTC, mononym requested changes

2022-05-24 09:16 UTC, mononym commented on en_US/rule/rule-engine_buildin_function.md
> +| `format_date` | Get the time and output the time string in the specified format | 1. time precision <br />2. time offset <br />3. time format string | string |
Perhaps shorten to `Get and output the time...`

2022-05-24 09:16 UTC, mononym commented on en_US/rule/rule-engine_buildin_function.md
> +micorsecond,
microsecond

2022-05-24 09:16 UTC, mononym commented on en_US/rule/rule-engine_buildin_function.md
> +The user can specify the time zone of the output time through this string, For example, the East Eight time zone can be represented by "+08:00". If the input is empty, the system default time zone wi
`...If the input is empty the system default time zone will be used.`

No need to put in a comma for that sentence.

2022-05-24 09:16 UTC, mononym commented on en_US/rule/rule-engine_buildin_function.md
> +The user can specify the time zone of the output time through this string, For example, the East Eight time zone can be represented by "+08:00". If the input is empty, the system default time zone wi
`The user can specify the time zone of the output time through this string.`

Put period at end instead of comma.

2022-05-24 09:16 UTC, mononym commented on zh_CN/rule/rule-engine_buildin_function.md
> +| micorsecond | 时间精确到微秒 |
microsecond

2022-05-30 08:03 UTC, DDDHuang approved these changes

2022-05-31 01:24 UTC, merged