feat: Alibaba Cloud Tablestore docs
emqtt/emq-docs-cn pull request #1176
Opened 2022-06-01 03:36 UTC by DDDHuang

2022-06-01 09:11 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +# 保存数据到 Alibaba Tablestore 数据库
Title should be in English

2022-06-01 09:16 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +`Table Name` and `ata Source` name, please fill in the `Table Name` and `Data Source` name as created (`Data Source` name can be empty string).
first `Data Source` is missing the D

2022-06-01 09:24 UTC, mononym requested changes

2022-06-01 09:24 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +| TimeStamp(microsecond) |In microsecondMQTT messages in EMQX are timestamped with millisecond precision by default and cannot be used directly. Fill in the blank value,the default value is the micro
I think the beginning `In microsecond` text is not supposed to be there? Perhaps should be deleted?

2022-06-01 09:24 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +| TimeStamp(microsecond) |In microsecondMQTT messages in EMQX are timestamped with millisecond precision by default and cannot be used directly. Fill in the blank value,the default value is the micro
What does it mean when it says `cannot be used directly`?

2022-06-01 09:24 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +| TimeStamp(microsecond) |In microsecondMQTT messages in EMQX are timestamped with millisecond precision by default and cannot be used directly. Fill in the blank value,the default value is the micro
Does putting a value here mean the timestamp is overwritten for all messages?

2022-06-01 09:24 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +| TimeSeries Cache | Tablestore identifies whether the current data needs to be created or updated with timeline metadata, enabled by default |
`metadata. Enabled by default`

2022-06-01 09:34 UTC, mononym requested changes

2022-06-01 09:34 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +Click on the `Time Series Table` created in the previous step to enter the timeline management.
```suggestion
Click on the `Time Series Table` created in the previous step to enter the timeline management UI.
```

2022-06-01 09:34 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +(This step can be skipped, Tablestore will automatically create a new `Time Series` when writing data that does not exist, the example does not operate on `Time Series`)
```suggestion
(This step can be skipped, Tablestore will automatically create a new `Time Series` when writing data that does not exist. The example does not operate on `Time Series`)
```

2022-06-01 09:34 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +`Table Name` and `ata Source` name, please fill in the `Table Name` and `Data Source` name as created (`Data Source` name can be empty string).
```suggestion
`Table Name` and `Data Source` name, please fill in the `Table Name` and `Data Source` name as created (`Data Source` name can be empty string).
```

2022-06-01 09:34 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +| TimeStamp(microsecond) |In microsecondMQTT messages in EMQX are timestamped with millisecond precision by default and cannot be used directly. Fill in the blank value,the default value is the micro
```suggestion
| TimeStamp(microsecond) | MQTT messages in EMQX are timestamped with millisecond precision by default and cannot be used directly. Fill in the blank value, the default value is the microsecond timestamp of the message arriving at EMQX |
```

2022-06-01 09:34 UTC, mononym commented on en_US/rule/backend_tablestore.md
> +| TimeSeries Cache | Tablestore identifies whether the current data needs to be created or updated with timeline metadata, enabled by default |
```suggestion
| TimeSeries Cache | Tablestore identifies whether the current data needs to be created or updated with timeline metadata. Enabled by default |
```

2022-06-02 12:55 UTC, gsychev commented on en_US/rule/backend_tablestore.md
> +Manage Time Series Table
```suggestion
## Manage Time Series Table
```

2022-06-02 12:56 UTC, gsychev commented on en_US/rule/backend_tablestore.md
> +Create a database instance (please refer to the official Tablestore documentation for the steps to create an instance).
```suggestion
## Create a database instance

> Please refer to the official Tablestore documentation for the steps to create an instance).
```

2022-06-02 12:58 UTC, gsychev commented on en_US/rule/backend_tablestore.md
> +These formats can be automatically recognized and classified by the rules engine. String-type data, however, is handled as binary data by default to ensure best compatibility. If you need to specify
```suggestion
These types can be automatically recognized and classified by the rules engine. String data, however, is handled as a binary by default to ensure the best compatibility. If you need to specify a field value as a string, you can fill the field into the `String Fields` when you create the action. After that, the engine will handle the field value as a string.
```

2022-06-06 01:40 UTC, DDDHuang commented on en_US/rule/backend_tablestore.md
> +| TimeStamp(microsecond) |In microsecondMQTT messages in EMQX are timestamped with millisecond precision by default and cannot be used directly. Fill in the blank value,the default value is the micro
Use 
```SQL
SELECT * FROM "#"
```
Rule engine will `SELECT` message's timestamp as a key-value, and it is in millisecond. 
But tablestore need microsecond timestamp.

2022-06-06 01:42 UTC, DDDHuang commented on en_US/rule/backend_tablestore.md
> +| TimeStamp(microsecond) |In microsecondMQTT messages in EMQX are timestamped with millisecond precision by default and cannot be used directly. Fill in the blank value,the default value is the micro
Only the timestamp written to the database will be overwritten.

2022-06-06 05:42 UTC, terry-xiaoyu approved these changes

2022-06-06 05:59 UTC, merged