docs: add listeners intro
emqtt/emq-docs-cn pull request #1339
Opened 2022-08-11 07:21 UTC by lafirest

2022-08-29 09:15 UTC, tigercl commented on zh_CN/getting-started/listeners.md
> +| Websocket Listener        | A listener for MQTT over WebSockets                     |
```suggestion
| Websocket Listener        | A listener for MQTT over WebSocket                     |
```

2022-08-29 09:15 UTC, tigercl commented on zh_CN/getting-started/listeners.md
> +| Secure Websocket Listener | A secure listener for MQTT over secure WebSockets (TLS) |
```suggestion
| Secure Websocket Listener | A secure listener for MQTT over secure WebSocket (TLS) |
```

2022-08-29 09:15 UTC, tigercl commented on zh_CN/getting-started/listeners.md
> +| QUIC Listener             | A secure listener for MQTT over secure WebSockets       |
```suggestion
| QUIC Listener             | A secure listener for MQTT over secure WebSocket       |
```

2022-08-29 09:16 UTC, tigercl commented on zh_CN/getting-started/listeners.md
> +由于默认配置的存在，我们能够非常快速地展示如何添加新的监听器，以 TCP 监听器为例，我们只需要在 `emqx.conf` 中添加以下一条配置即可：
```suggestion
由于默认配置的存在，我们能够非常快速地添加新的监听器，以 TCP 监听器为例，我们只需要在 `emqx.conf` 中添加以下一条配置即可：
```

2022-08-29 09:18 UTC, tigercl commented on zh_CN/getting-started/listeners.md
> +在 API 文档中有，有更多和更详细的监听器 API 信息，这里就不再一一列举了。
```suggestion
更详细的监听器 API 信息，请参加 [API 文档](xxx.md)
```
文档里面尽量不要出现类似于博客的写法。

2022-08-29 09:19 UTC, tigercl commented on zh_CN/getting-started/listeners.md
> +     'http://127.0.0.1:18083/api/v5/listeners/tcp%3Ademo' \
这里需要解释一下为什么是 `tcp%3Ademo`

2022-08-30 01:35 UTC, wivwiv requested changes

2022-08-30 01:35 UTC, wivwiv commented on en_US/getting-started/listeners.md
> +<a id="org67b1907"></a>
What is a tag used for?

2022-08-30 01:35 UTC, wivwiv commented on zh_CN/getting-started/listeners.md
> +| 1883            | MQTT/TCP protocol port  |
To be more strict, 1883 should be at the top of the list

2022-08-30 01:35 UTC, wivwiv commented on zh_CN/getting-started/listeners.md
> +     'http://127.0.0.1:18083/api/v5/listeners/tcp%3Ademo' \
先给出 API 文档，再给出示例。更多 API 可以 Link 到 API 章节。

```
POST http://127.0.0.1:1883/api/v5/listeners/{type}:{name}
```

2022-09-15 05:36 UTC, HJianBo approved these changes, later dismissed

2022-09-15 05:36 UTC, HJianBo commented on zh_CN/getting-started/listeners.md
> +监听器主要用于配置不同协议的监听端口和相关参数，EMQX 支持配置多个 Listener 以同时监听多个协议或端口。
```suggestion
监听器主要用于配置不同协议的监听端口和相关参数，EMQX 支持配置多个监听器以同时监听多个协议或端口。
```

2022-09-15 05:39 UTC, HJianBo approved these changes
Look goods to me. let's merge it as soon as possible

2022-09-15 05:40 UTC, merged