docs(lw): sync from v4.4
emqtt/emq-docs-cn pull request #1456
Opened 2022-10-25 09:06 UTC by lafirest

2022-11-01 11:09 UTC, zmstone approved these changes

2022-11-01 11:10 UTC, zmstone requested changes

2022-11-01 11:10 UTC, zmstone commented on 4.3
> +branch 'sync/4.4-' set up to track 'origin/release-4.3'.
sorry, what's this?

2022-11-02 08:24 UTC, lafirest commented on 4.3
> +branch 'sync/4.4-' set up to track 'origin/release-4.3'.
I have deleted it

2022-11-03 10:40 UTC, zmstone approved these changes

2022-11-04 01:48 UTC, merged