Fix community feedback
emqtt/emq-docs-cn pull request #1506
Opened 2022-11-27 13:44 UTC by wivwiv

2023-02-01 02:14 UTC, LenaLenaPan commented on en_US/README.md
> +- **Massive Scale**: Scale to 100 million concurrent MQTT connections with a single EMQX 5.0 cluster, In 4.x this number is 10 million.
```suggestion
- **Massive Scale**: The number of concurrent MQTT sessions supported by one EMQX cluster has been increased from 10 million to 100 million. 
```

2023-02-01 02:15 UTC, LenaLenaPan commented on en_US/README.md
> +- **Massive Scale**: Scale to 100 million concurrent MQTT connections with a single EMQX 5.0 cluster, In 4.x this number is 10 million.
我拿掉了4.x版本，觉得这个信息没有从10到100那么重要

2023-02-01 02:43 UTC, LenaLenaPan requested changes

2023-02-01 02:43 UTC, LenaLenaPan commented on en_US/getting-started/log.md
> +When starting with the `emqx console` command, the startup script overrides `log.to` with the environment variable to set it to `console`, and the logs are not output to file.
```suggestion
By default, the log files will be output as files. However, when starting with the `emqx console` command, the startup script will set `log.to = console` by environment variable and the log files will be generated to the console.
```

2023-02-01 02:43 UTC, LenaLenaPan commented on zh_CN/getting-started/log.md
> +通过 `emqx console` 命令启动时，启动脚本通过环境变量覆盖 `log.to` 将其设置为 `console`，此时日志无法输出到文件。
```suggestion
默认情况下，日志文件会作为文件输出，但当通过 `emqx console` 命令启动时，启动脚本通过环境变量设置 `log.to = console`，此时日志将通过 console 输出。
```

2023-03-22 07:10 UTC, wivwiv commented on en_US/README.md
> +- **Massive Scale**: Scale to 100 million concurrent MQTT connections with a single EMQX 5.0 cluster, In 4.x this number is 10 million.
4.x 不支持 100M，这个数字会引起用户的误解

2023-06-08 06:13 UTC, Meggielqk commented on en_US/getting-started/log.md
> +By default, the log files will be output as files. However, when starting with the `emqx console` command, the startup script will set `log.to = console` by environment variable and the log files wil
```suggestion
By default, the log data will be output to files. However, when starting with the `emqx console` command, the startup script will set `log.to = console` by environment variable. In that case, the log data will be output to the console.
```

2023-06-08 06:14 UTC, Meggielqk commented on zh_CN/getting-started/log.md
> +默认情况下，日志文件会作为文件输出，但当通过 `emqx console` 命令启动时，启动脚本通过环境变量设置 `log.to = console`，此时日志将通过 console 输出。
```suggestion
默认情况下，日志文件会作为文件输出。但当通过 `emqx console` 命令启动时，启动脚本通过环境变量设置 `log.to = console`，此时日志将通过 console 输出。
```

2023-07-20 03:45 UTC, Meggielqk approved these changes, later dismissed

2023-07-20 03:54 UTC, LenaLenaPan approved these changes, later dismissed

2023-07-20 07:31 UTC, id commented on en_US/getting-started/log.md
> +By default, the log data will be output to files. However, when starting with the `emqx console` command, the startup script will set `log.to = console` by environment variable. In that case, the log
```suggestion
By default, the log data will be written to files. However, when starting node with the `emqx console` command, the startup script will will apply the 'log.to = console' setting. As a result, the log data will be directed to the console instead.
```

2023-07-21 07:11 UTC, id approved these changes

2023-07-31 02:07 UTC, merged