Update quickstart part
emqtt/emq-docs-cn pull request #1544
Opened 2023-01-04 10:00 UTC by LenaLenaPan

2023-01-04 10:02 UTC, LenaLenaPan commented on zh_CN/getting-started/getting-started.md
> +4. 此时我们通过点击左侧导航栏的**仪表盘**返回主界面，在**概览**页签，可以看到当前的连接数，主题数、以及订阅数，节点信息，以及实时的消息发送及接收情况
```suggestion
4. 此时我们通过点击左侧导航栏的**仪表盘**返回主界面，在**概览**页签，可以看到当前的连接数，主题数、以及订阅数，节点信息，以及实时的消息发送及接收情况。
```

2023-01-05 01:39 UTC, LenaLenaPan commented on zh_CN/getting-started/getting-started.md
> +## 使用 Dashboard WebSocket  快速验证
```suggestion
## 使用 Dashboard WebSocket 快速验证
```

2023-01-05 01:39 UTC, LenaLenaPan commented on zh_CN/getting-started/getting-started.md
> +在 Dashboard 页面，点击左侧导航栏的 **问题分析 -> WebSocket 客户端**，即可进入相关页面。您可按照如下步骤完成客户端与 EMQX 的连接、订阅相关主题，并测试消息的接受情况。
```suggestion
在 Dashboard 页面，点击左侧导航栏的 **问题分析 -> WebSocket 客户端**，即可进入相关页面。您可按照如下步骤完成客户端与 EMQX 的连接、订阅相关主题，并测试消息的接收情况。
```

2023-01-05 03:26 UTC, wivwiv requested changes

2023-01-05 03:26 UTC, wivwiv commented on zh_CN/getting-started/getting-started.md
> +本章节将带您从下载安装开始，带您体验从启动 EMQX 服务，到通过 Websocket 或 MQTT 客户端测试连接的完整流程，带您感受 EMQX 的强大功能。
这里只是体验了基本功能。
```suggestion
本章节将带您从下载安装开始，带您体验从启动 EMQX 服务，到通过 WebSocket 工具或 MQTT 客户端测试连接并进行消息发布订阅的完整流程。
```

2023-01-05 03:26 UTC, wivwiv commented on zh_CN/getting-started/getting-started.md
> +接下来我们将通过 Dashboard 自带的 Websocket 进行连接测试。
```suggestion
接下来我们将通过 Dashboard 自带的 WebSocket 工具进行连接测试。
```

2023-01-05 03:26 UTC, wivwiv commented on zh_CN/getting-started/getting-started.md
> +## 使用 Dashboard WebSocket 快速验证
```suggestion
## 使用 Dashboard WebSocket 工具快速验证
```

2023-01-05 03:26 UTC, wivwiv commented on zh_CN/getting-started/getting-started.md
> +EMQX 提供了标准的 MQTT 协议支持，启动后即可接入 MQTT 客户端，本节我们将演示如何通过 Dashboard 自带的 WebSocket 客户端工具接入 EMQX，从而进行消息通信验证。
这里介绍的是 WebSocket，需要特别声明一下是通过 MQTT over WebSocket 接入的，避免引起用户误解。
```suggestion
EMQX 提供了标准的 MQTT 协议包括 MQTT over WebSocket 支持，启动后即可接入 MQTT 客户端，本节我们将演示如何通过 Dashboard 自带的 WebSocket 客户端工具接入 EMQX，从而进行消息通信验证。
```

2023-01-05 03:26 UTC, wivwiv commented on zh_CN/getting-started/getting-started.md
> +![image-20230104173034300](./assets/emqx-websocket.png)
不要出现空白或无意义的 alt，这个内容可以描述图像的文本，用于在图像无法显示时代替图像，并且对 SEO 比较友好（使用相应关键词搜索图片的时候可以搜到我们）。
```suggestion
![EMQX MQTT WebSocket 连接](./assets/emqx-websocket.png)
```

2023-01-05 08:20 UTC, LenaLenaPan commented on en_US/getting-started/getting-started.md
> +2. Start your web browser and enter http://localhost:18083/ ( `localhost` can be substituted with your IP address) in the address bar to access the  [EMQX Dashboard](./dashboard/introduction.md) (htt
```suggestion
2. Start your web browser and enter `http://localhost:18083/` ( `localhost` can be substituted with your IP address) in the address bar to access the  [EMQX Dashboard](./dashboard/introduction.md), from where you can connect to your clients or check the running status. 
```

2023-01-05 08:21 UTC, LenaLenaPan commented on zh_CN/getting-started/getting-started.md
> +2. 通过浏览器访问 [http://localhost:18083/](http://localhost:18083/)（localhost 可替换为您的实际 IP 地址）以访问 [EMQX Dashboard](./dashboard/introduction.md) 管理控制台，进行设备连接与相关指标监控管理。
```suggestion
2. 通过浏览器访问 [http://localhost:18083/](http://localhost:18083/)（`localhost` 可替换为您的实际 IP 地址）以访问 [EMQX Dashboard](./dashboard/introduction.md) 管理控制台，进行设备连接与相关指标监控管理。
```

2023-01-05 09:03 UTC, wivwiv commented on zh_CN/getting-started/getting-started.md
> +在本篇快速上手中，我们将带您通过容器化部署或压缩包的形式快速体验 EMQX。
压缩包（名词）的形式感觉不太对
```suggestion
在本篇快速上手中，我们将带您通过容器化部署或解压安装的形式快速体验 EMQX。
```

2023-01-05 09:03 UTC, wivwiv commented on zh_CN/getting-started/getting-started.md
> +除了私有部署外，我们也提供了全托管的 EMQX Cloud 服务，您只需几步注册即可轻松体验 EMQX 提供的 MQTT 消息服务，欢迎前往 [EMQX Cloud 门户](https://cloud.emqx.io/)页面免费试用。
```suggestion
除了私有部署外，我们也提供了全托管的 EMQX Cloud 服务，您只需几步注册即可轻松体验 EMQX 提供的 MQTT 消息服务，欢迎前往 [EMQX Cloud 门户](https://cloud.emqx.com/)页面免费试用。
```

2023-01-06 07:04 UTC, wivwiv approved these changes

2023-01-06 07:23 UTC, merged