update Chinese part of MQTT data bridge
emqtt/emq-docs-cn pull request #1624
Opened 2023-01-29 10:10 UTC by LenaLenaPan

2023-01-29 10:21 UTC, wivwiv requested changes

2023-01-29 10:21 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mqtt.md
> +EMQX 支持通过 MQTT 连接多个 EMQX 集群或其他 MQTT 服务，其工作原理如下：
桥接是一个很常见的概念，这里需要声明这个功能是桥接，并介绍 MQTT 数据桥接的定义，改过之后没有了这层意思

2023-01-29 10:21 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mqtt.md
> +7. **入口配置**（可选）：配置桥接规则，将远程 MQTT 服务上的消息转发到本地；我们希望订阅 `remote/topic/ingress ` 下的消息，并将收到的信息转发至 `local/topic/ingress` 主题，因此将进入如下配置：
消息
```suggestion
7. **入口配置**（可选）：配置桥接规则，将远程 MQTT 服务上的消息转发到本地；我们希望订阅 `remote/topic/ingress` 下的消息，并将其转发至 `local/topic/ingress` 主题，因此将进入如下配置：
```

2023-01-29 10:21 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mqtt.md
> +      - **主题**：在集群工作模式下，我们将通过[共享订阅](../mqtt/mqtt-shared-subscription.md)来避免消息重复，因此填入 `$share/g/remote/topic/ingress`
这里应当明确告诉用户有两种选择，因为有的 MQTT 服务不支持共享订阅。
- EMQX 单节点运行时，填入任意主题即可
- （如果）EMQX 集群运行时，需要使用共享订阅

2023-01-29 10:21 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mqtt.md
> +   - **本地 MQTT 服务**：将订阅得到的消息发布到指定主题中，也可以留空，此时将通过规则处理后使用 [消息重发布](./rules.md#消息重发布) 动作转发。
留空不代表就能够转发，还需要手动配置规则

```suggestion
   - **本地 MQTT 服务**：将订阅得到的消息发布到指定主题中，也可以留空，通过配置规则处理并使用 [消息重发布](./rules.md#消息重发布) 动作转发。
```

2023-01-29 10:23 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mqtt.md
> +EMQX 支持通过 MQTT 连接多个 EMQX 集群或其他 MQTT 服务，其工作原理如下：
```suggestion
MQTT 数据桥接是一种连接多个 EMQX 集群或其他 MQTT 服务的方式，其工作原理如下：
```

2023-01-30 01:44 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-gcp-pubsub.md
>  # GCP PubSub桥
```suggestion
# GCP PubSub
```

2023-01-30 01:44 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-gcp-pubsub.md
> +EMQX GCP PubSub 集成可以发送MQTT消息和事件到
```suggestion
EMQX GCP PubSub 集成可以发送 MQTT 消息和事件到
```

2023-01-30 01:45 UTC, merged