Updated Retained message
emqtt/emq-docs-cn pull request #1733
Opened 2023-03-20 08:20 UTC by Meggielqk

2023-03-20 13:22 UTC, LenaLenaPan requested changes

2023-03-20 13:22 UTC, LenaLenaPan commented on en_US/messaging/explore-mqtt.md
> +The retained message feature enables the subscribers actively fetch messages from publishers. New subscribers who subscribes to the same topic also can get the latest message immediately without wait
as discussed, let's stat why we need this feature, then how to use this feature.

2023-03-20 13:22 UTC, LenaLenaPan commented on en_US/messaging/explore-mqtt.md
> +   - The `Host` is by default set to the name of [public MQTT Broker](https://www.emqx.com/en/mqtt/public-mqtt5-broker) provided by [EMQX Cloud](https://www.emqx.com/en/cloud).
this is incorrect, it is a manual about enterprise, cloud should not be here, and how to obtain the IP and port number should be added, also the protocol selection step is missing.

2023-03-20 13:22 UTC, LenaLenaPan commented on en_US/messaging/explore-mqtt.md
> +     You can also use your localhost name `127.0.0.1`.
this is only an example.

2023-03-20 13:22 UTC, LenaLenaPan commented on en_US/messaging/explore-mqtt.md
> +   1. Type the topic heading `sensor/t1` in the text box.
these 3 little steps can be integrated with Step 3.

2023-03-20 13:22 UTC, LenaLenaPan commented on en_US/messaging/explore-mqtt.md
> +6. Input `sensor/+` in the **Topic** text box. Click the **Confirm** button.
step 5 and step 6 can be merged

2023-03-20 13:22 UTC, LenaLenaPan commented on en_US/messaging/explore-mqtt.md
> +   With topic set to `sensor/+`, both `sensor/t1` and `sensor/t2` are subscribed. For more information on topics and wildcards, see [Understanding MQTT Topics & Wildcards by Case](https://www.emqx.co
let's use # rather than +

2023-03-20 13:22 UTC, LenaLenaPan commented on en_US/messaging/explore-mqtt.md
> +   The normal message under the topic `sensor/t1` and the first retained message under the topic `sensor/t2` are not received. The MQTT broker only stores the latest retained message for each topic.
as in this manual, let's use EMQX rather than MQTT broker, and let's focus on what will happen part "EMQX only stores the latest retained message for each topic. You can also check the received retained message on EMQX Dashboard (xx -> xxx)."

2023-04-03 05:29 UTC, Meggielqk commented on en_US/messaging/explore-mqtt.md
> +     You can also use your localhost name `127.0.0.1`.
Updated in the file

2023-04-03 06:52 UTC, closed without merging