Fixed QA issues in EMQX-9205
emqtt/emq-docs-cn pull request #1744
Opened 2023-03-23 02:55 UTC by Meggielqk

2023-03-23 10:06 UTC, LenaLenaPan approved these changes, later dismissed

2023-03-23 10:10 UTC, HJianBo approved these changes, later dismissed

2023-03-27 01:31 UTC, LenaLenaPan requested changes
please update english accordingly

2023-04-04 05:19 UTC, LenaLenaPan submitted a review, later dismissed

2023-04-04 05:20 UTC, LenaLenaPan approved these changes

2023-04-04 05:20 UTC, merged