Publish/subscribe
emqtt/emq-docs-cn pull request #1776
Opened 2023-04-03 09:25 UTC by Meggielqk

2023-04-11 05:34 UTC, LenaLenaPan commented on en_US/messaging/mqtt-auto-subscription.md
> +## Try Auto Subscription using MQTT X Client
```suggestion
## Try Auto Subscription Using MQTT X Client
```

2023-04-11 05:43 UTC, LenaLenaPan commented on en_US/messaging/mqtt-shared-subscription.md
> +The following procedure demonstrates how to form groups for multiple subscribers and make them subscribe to the same topic. In this demonstration, you can create three subscribers `Subscriber1`, `Sub
```suggestion
The following procedure demonstrates how to group multiple subscribers and make them subscribe to the same topic. In this demonstration, you can create three subscribers `Subscriber1`, `Subscriber2` and `Subscriber3,` and divide them into groups `a` and `b`. Both groups subscribe to the topic `t/1`. 
```

2023-04-11 05:43 UTC, LenaLenaPan commented on en_US/messaging/mqtt-shared-subscription.md
> +The following procedure demonstrates how to form groups for multiple subscribers and make them subscribe to the same topic. In this demonstration, you can create three subscribers `Subscriber1`, `Sub
这里其实还建了一个 demo connection，要不要说下这个 demo connection 的目的？

2023-04-11 05:45 UTC, LenaLenaPan commented on en_US/messaging/publish-and-subscribe.md
> +It is more safe and efficient for the developers to test the EMQX messaging services using client tools before connecting the real-time devices to the EMQX broker and developing the IoT applications.
```suggestion
It is more safe and efficient for the developers to test the EMQX messaging services using client tools before connecting the real-time devices to the EMQX and developing the IoT applications.
```

2023-04-11 05:47 UTC, LenaLenaPan reviewed
add some comments

2023-04-11 05:47 UTC, LenaLenaPan commented on en_US/messaging/mqtt-delayed-publish.md
> +Delayed publish is an extended MQTT feature supported by EMQX. When a client publishes a message to EMQX broker with the topic prefix `$delayed/{DelayInteval}`, it triggers the delayed publish featur
```suggestion
Delayed publish is an extended MQTT feature supported by EMQX. When a client publishes a message to EMQX with the topic prefix `$delayed/{DelayInteval}`, it triggers the delayed publish feature. The messages will be published after a period of time predefined by the user. 
```

2023-04-11 05:47 UTC, LenaLenaPan commented on en_US/messaging/mqtt-retained-message.md
> +EMQX implements the retained message feature of MQTT. You can flag one message published under a certain topic as `Retained` and save it as a persistent message on the EMQX broker. When any new subsc
```suggestion
EMQX implements the retained message feature of MQTT. You can flag one message published under a certain topic as `Retained` and save it as a persistent message on the EMQX. When any new subscribers subscribe to a topic that matches the topic of the retained message, they immediately receive that message, even if it was published before they subscribed to the topic.
```

2023-04-11 05:48 UTC, LenaLenaPan commented on en_US/messaging/mqtt-shared-subscription.md
> +When the message of the shared subscription is published, the EMQX broker forwards the message to different groups at the same time, but only one of the subscribers in the same group receives the mes
```suggestion
When the message of the shared subscription is published, the EMQX forwards the message to different groups at the same time, but only one of the subscribers in the same group receives the message at a time.
```

2023-04-11 05:49 UTC, LenaLenaPan commented on en_US/messaging/mqtt-will-message.md
> +You can use client tools to test this messaging service in EMQX. This section introduces how to use the [MQTT X Client](https://mqttx.app/) and [MQTT X CLI](https://mqttx.app/cli) to simulate clients
```suggestion
You can use client tools to try this messaging service in EMQX. This section introduces how to use the [MQTT X Client](https://mqttx.app/) and [MQTT X CLI](https://mqttx.app/cli) to simulate clients and see how a will message is published and received.
```

2023-04-11 05:49 UTC, LenaLenaPan commented on en_US/messaging/mqtt-retained-message.md
> +You can use client tools to test this messaging service in EMQX. This section introduces how to use the [MQTT X Client](https://mqttx.app/) and [MQTT X CLI](https://mqttx.app/cli) to simulate clients
```suggestion
You can use client tools to try this messaging service in EMQX. This section introduces how to use the [MQTT X Client](https://mqttx.app/) and [MQTT X CLI](https://mqttx.app/cli) to simulate clients and see how a retained message is published and received.
```

2023-04-11 05:49 UTC, LenaLenaPan reviewed
leave some comments

2023-04-12 14:05 UTC, wivwiv requested changes
Not yet review finished

2023-04-12 14:05 UTC, wivwiv commented on en_US/messaging/explore-mqtt.md
> +- The client closes the network connection before sending offline packets.
Strictly speaking, it should be called DISCONNECT packet

```suggestion
- The client closes the network connection before sending DISCONNECT packet.
```

2023-04-12 14:05 UTC, wivwiv commented on en_US/messaging/explore-mqtt.md
> +- The server closes the network connection before receiving the offline packet.
```suggestion
- The server closes the network connection before receiving the DISCONNECT packet.
```

2023-04-18 02:49 UTC, wivwiv approved these changes

2023-04-18 09:43 UTC, merged