docs: update limiter docs
emqtt/emq-docs-cn pull request #1817
Opened 2023-04-19 03:55 UTC by lafirest

2023-04-19 05:33 UTC, LenaLenaPan commented
it this a feature that will be released with e.5.0.3 or already supported? @lafirest

2023-04-19 05:49 UTC, lafirest commented
> 

@LenaLenaPan  Yes, the modification of codes has already merged.

2023-04-20 02:59 UTC, HJianBo commented
Wait a moment, I checked the code for relealse-50 and found that it does not include this modification for limiter! Are you sure it will be included in the e5.0.3 release? @lafirest 

@LenaLenaPan We should make use of the milestone field so that we don't have to confirm multiple times which version this document's modifications should be included in. WDYT?

2023-05-18 03:28 UTC, zhongwencool commented on en_US/rate-limit/rate-limit.md
>    max_connections = 1024000
we should delete `max_connections`. This can be misleading to users

2023-05-18 03:28 UTC, zhongwencool commented on zh_CN/rate-limit/rate-limit.md
>    max_connections = 1024000
delete max_connection

2023-05-30 14:44 UTC, wivwiv requested changes

2023-05-30 14:44 UTC, wivwiv commented on zh_CN/rate-limit/rate-limit.md
> +| bytes_rate      | 每秒流入的消息的字节数大小       | 暂停接收客户端消息     |
```suggestion
| bytes_rate      | 单个客户端每秒流入的消息的字节数大小       | 暂停接收客户端消息     |
```

2023-05-30 14:44 UTC, wivwiv commented on zh_CN/rate-limit/rate-limit.md
> +| messages_rate   | 每秒流入的消息条数             | 暂停接收客户端消息     |
```suggestion
| messages_rate   | 单个客户端每秒流入的消息条数             | 暂停接收客户端消息     |
```

2023-05-30 14:44 UTC, wivwiv commented on zh_CN/rate-limit/rate-limit.md
> +## 为监听器设置速率限制
```suggestion
```

2023-05-30 14:44 UTC, wivwiv commented on zh_CN/rate-limit/rate-limit.md
> +| max_conn_rate   | 每秒的连接数                  | 暂停接收新的连接       |
```suggestion
| max_conn_rate   | 当前监听器每秒的连接数                  | 暂停接收新的连接       |
```

2023-05-30 14:44 UTC, wivwiv commented on en_US/configuration/limiter.md
> +| `bytes_rate`    | Data Publish Rate       | Incoming message size in bytes per second | Pause receiving client messages |
```suggestion
| `bytes_rate`    | Data Publish Rate per Client       | Incoming message size in bytes per second | Pause receiving client messages |
```

2023-05-30 14:44 UTC, wivwiv commented on en_US/configuration/limiter.md
> +| `message_rate`  | Messages Publish Rate   | Incoming messages per second              | Pause receiving client messages |
```suggestion
| `message_rate`  | Messages Publish Rate per Client   | Incoming messages per second              | Pause receiving client messages |
```

2023-05-30 14:44 UTC, wivwiv commented on en_US/configuration/limiter.md
> +| `max_conn_rate` | Maximum Connection Rate | Connections per second                    | Pause receiving new connections |
```suggestion
| `max_conn_rate` | Maximum Connection Rate per Listener | Connections per second                    | Pause receiving new connections |
```

2023-05-30 14:44 UTC, wivwiv commented on en_US/rate-limit/rate-limit.md
> +| bytes_rate    | Incoming message size in bytes per second | Pause receiving client messages |
```suggestion
| bytes_rate    | Incoming message size in bytes per second  per client | Pause receiving client messages |
```

2023-05-30 14:44 UTC, wivwiv commented on en_US/rate-limit/rate-limit.md
> +| messages_rate | Incoming messages per second              | Pause receiving client messages |
```suggestion
| messages_rate | Incoming messages per second  per client             | Pause receiving client messages |
```

2023-05-30 14:44 UTC, wivwiv commented on en_US/rate-limit/rate-limit.md
> +| max_conn_rate | Connections per second                    | Pause receiving new connections |
```suggestion
| max_conn_rate | Connections per second  per listener                    | Pause receiving new connections |
```

2023-05-30 14:44 UTC, wivwiv requested changes

2023-05-30 14:44 UTC, wivwiv commented on en_US/rate-limit/rate-limit.md
> +## Configure Limiter on Listener
```suggestion
```

2023-06-01 01:22 UTC, HJianBo commented on zh_CN/rate-limit/rate-limit.md
> +限制器可以在监听器级别上工作。例如，要为默认的TCP监听器设置限制器，可以使用以下代码进行操作：
```suggestion
限制器可以在监听器级别上工作。例如，要为默认的TCP监听器设置限制器，可以在 emqx.conf 中按以下进行配置：
```

2023-06-01 01:22 UTC, HJianBo commented on en_US/rate-limit/rate-limit.md
> +Limiter can work on the listener level. For example, to set a Limiter for the default TCP listener, you can work with the code below:
```suggestion
Limiter can work on the listener level. For example, to set a Limiter for the default TCP listener, You can configure it in emqx.conf as follows:
```

2023-06-01 01:23 UTC, HJianBo approved these changes

2023-06-02 07:39 UTC, wivwiv approved these changes

2023-06-02 07:39 UTC, merged