rewrite coap gateway
emqtt/emq-docs-cn pull request #1824
Opened 2023-04-20 12:34 UTC by LenaLenaPan

2023-04-20 12:50 UTC, LenaLenaPan commented on en_US/gateway/coap.md
> +## Reference: CoAP Client Guide in Connection Mode
```suggestion
## Reference: CoAP Client Guide
```

2023-04-22 08:04 UTC, HJianBo requested changes

2023-04-22 08:04 UTC, hjianbo commented on en_US/gateway/coap.md
> +In EMQX 5.0, CoAP gateways can be configured and enabled through the Dashboard, HTTP API, and configuration file `emqx.conf`. This section takes the configuration via Dashboard as an example to illus
typo?
CoAP gateways -> CoAP gateway

2023-04-22 08:04 UTC, hjianbo commented on en_US/gateway/coap.md
> +  - **non**: The CoAP Notification need not be acknowledged by the client.
```suggestion
  - **non**: The CoAP notification need not be acknowledged by the client. 
```

2023-04-22 08:04 UTC, hjianbo commented on en_US/gateway/coap.md
> +- **MountPoint**: Set a string that is prefixed to all topics when publishing or subscribing, providing a way to implement message routing isolation between different listeners, for example, *mqttsn*
```suggestion
- **MountPoint**: Set a string that is prefixed to all topics when publishing or subscribing, providing a way to implement message routing isolation between different protocols, for example, *MQTT-SN*.
```

2023-04-22 08:04 UTC, hjianbo commented on en_US/gateway/coap.md
> +  **Note**: The prefixed string will be removed from the topic name when the message is delivered to the subscriber.
It is more accurate, I think:

This topic prefix is managed by the gateway. CoAP clients do not need to add this prefix explicitly when publishing and subscribing.

2023-04-22 08:04 UTC, HJianBo commented on en_US/gateway/coap.md
> +By default, one UPD listener with the name of **default** is already configured on port `5683`, which supports up to 1,024,000 concurrent connections. You can click **Settings** for more customized s
Typos:
UPD listener -> UDP listener

2023-04-22 08:04 UTC, HJianBo commented on en_US/gateway/coap.md
> +<img src="/Users/lena/Documents/GitHub/rebalancing/emqx-docs/en_US/gateway/assets/mqttsn-listerner.png" alt="MQTTSN listener" style="zoom:50%;" />
Invalid image path

2023-04-23 01:59 UTC, LenaLenaPan commented on en_US/gateway/coap.md
> +In EMQX 5.0, CoAP gateways can be configured and enabled through the Dashboard, HTTP API, and configuration file `emqx.conf`. This section takes the configuration via Dashboard as an example to illus
```suggestion
In EMQX 5.0, CoAP gateway can be configured and enabled through the Dashboard, HTTP API, and configuration file `emqx.conf`. This section takes the configuration via Dashboard as an example to illustrate the operating steps. 
```

2023-04-23 02:01 UTC, LenaLenaPan commented on en_US/gateway/coap.md
> +  **Note**: The prefixed string will be removed from the topic name when the message is delivered to the subscriber.
```suggestion
  **Note**: This topic prefix is managed by the gateway. CoAP clients do not need to add this prefix explicitly when publishing and subscribing.
```

2023-04-23 02:01 UTC, LenaLenaPan commented on en_US/gateway/coap.md
> +By default, one UPD listener with the name of **default** is already configured on port `5683`, which supports up to 1,024,000 concurrent connections. You can click **Settings** for more customized s
```suggestion
By default, one UDP listener with the name of **default** is already configured on port `5683`, which supports up to 1,024,000 concurrent connections. You can click **Settings** for more customized settings for **Delete** to delete the listener. Or click **Add Listener** to add a new listener.
```

2023-04-23 02:01 UTC, LenaLenaPan commented on en_US/gateway/coap.md
> +<img src="/Users/lena/Documents/GitHub/rebalancing/emqx-docs/en_US/gateway/assets/mqttsn-listerner.png" alt="MQTTSN listener" style="zoom:50%;" />
```suggestion
<img src="./assets/mqttsn-listerner.png" alt="MQTTSN listener" style="zoom:50%;" />
```

2023-04-23 05:46 UTC, HJianBo commented on en_US/gateway/mqttsn.md
> +- **MountPoint**: Set a string that is prefixed to all topics when publishing or subscribing, providing a way to implement message routing isolation between different protocols, for example, *MQTT-SN
```suggestion
- **MountPoint**: Set a string that is prefixed to all topics when publishing or subscribing, providing a way to implement message routing isolation between different protocols, for example, `mqttsn/`.
```

2023-04-23 05:48 UTC, HJianBo commented on en_US/gateway/mqttsn.md
> +  **Note**: This topic prefix is managed by the gateway. CoAP clients do not need to add this prefix explicitly when publishing and subscribing.
```suggestion
  **Note**: This topic prefix is managed by the gateway. MQTT-SN clients do not need to add this prefix explicitly when publishing and subscribing.
```

2023-04-23 07:08 UTC, HJianBo approved these changes

2023-04-26 06:27 UTC, wivwiv approved these changes

2023-04-27 05:43 UTC, merged