Rewrote Log and Observability
emqtt/emq-docs-cn pull request #1830
Opened 2023-04-24 05:03 UTC by Meggielqk

2023-04-26 14:17 UTC, wivwiv requested changes

2023-04-26 14:17 UTC, wivwiv commented on en_US/observability/alarms.md
> +
```suggestion
The log level is `warning`, and the `msg` field is `alarm_is_activated` and `alarm_is_deactivated`.
```

2023-04-26 14:17 UTC, wivwiv commented on en_US/observability/alarms.md
> +| alarm.actions         | Actions of writing the alarm to log (console or file) and publishing the alarm as an MQTT message to the system topics `$SYS/brokers/emqx@xx.xx.xx.x/alarms/activate` and `$S
```suggestion
| alarm.actions         | Actions of writing the alarm to log (console or file) and publishing the alarm as an MQTT message to the system topics `$SYS/brokers/<node_name>/alarms/activate` and `$SYS/brokers/<node_name>/alarms/deactivate`. The actions are triggered when the alarm is activated or deactivated. | `["log", "publish"]` | -               |
```

2023-04-26 14:17 UTC, wivwiv commented on en_US/observability/topic-metrics.md
> +- **Outgoing Messages**: Messages routed by MEQX every second on the monitored topic.
```suggestion
- **Outgoing Messages**: Messages routed by EMQX every second on the monitored topic.
```

2023-04-26 14:17 UTC, wivwiv commented on en_US/observability/topic-metrics.md
> +- **Incoming messages**: Messages received by EMQX every second on the monitored topic.
```suggestion
- **Incoming messages**:  The total number of message incoming on the current topic and the number of message incoming per second.
```

2023-04-26 14:17 UTC, wivwiv commented on en_US/observability/topic-metrics.md
> +- **Outgoing Messages**: Messages routed by MEQX every second on the monitored topic.
```suggestion
- **Outgoing Messages**: The total number of message outgoing on the current topic and the number of message outgoing per second.
```

2023-04-26 14:17 UTC, wivwiv commented on en_US/observability/topic-metrics.md
> +- **Dropped Messages**: Messages are dropped by EMQX every second on the monitored topic.
```suggestion
- **Dropped Messages**: The total number of message dropped on the current topic and the number of message dropped per second.
```

2023-05-04 09:51 UTC, wivwiv requested changes

2023-05-04 09:51 UTC, wivwiv commented on en_US/observability/alarms.md
> +EMQX provides you with various ways to get alarms and check the detailed alarm formation. One way is to view the alarms on EMQX Dashboard, where you can view a list of active or historical alarms. Ho
```suggestion
EMQX provides you with various ways to get alarms and check the detailed alarm formation. One way is to view the alarms on EMQX Dashboard, where you can view a list of active or historical alarms. However, it is only a central place for easy access to an overview of alarms that have been triggered. Another way is to subscribe to system topics through MQTT to receive real-time notifications of alarms with detailed alarm information. Alarms can also be accessed from the log or via REST API.
```

2023-05-04 09:51 UTC, wivwiv commented on en_US/observability/metrics-and-stats.md
>  #### Connections
- client.connack：客户端收到连接确认（CONNACK）消息的次数，包括成功和失败的连接请求。
- client.connect：客户端发起连接请求的次数，包括成功和失败的连接请求。
- client.connected：客户端已成功连接的次数。
- client.disconnected：客户端断开连接的次数，包括主动断开和非正常断开。
- client.subscribe：客户端成功订阅主题的次数。
- client.unsubscribe：客户端成功取消订阅主题的次数。

2023-05-05 09:46 UTC, zhongwencool submitted a review, later dismissed

2023-05-05 09:46 UTC, zhongwencool commented on en_US/observability/metrics-and-stats.md
>  #### Connections
包括成功和失败的连接请求，这个具体是什么意思，感觉有点无法理解，什么叫失败的连接请求？
直接说收到CONNACK指令的次数应该就明确了吧。

2023-05-06 07:33 UTC, wivwiv commented on en_US/observability/metrics-and-stats.md
>  #### Connections
> 

同意，CONNACK 就要不要后半句了

2023-05-06 09:23 UTC, LenaLenaPan reviewed
leave some comments

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +- Metrics are integer-type counters used to measure simple incrementing and decrementing numbers, such as the number of sent bytes and messages.
```suggestion
- Metrics are integer-type counters used to measure simple incrementing and decrementing numbers, such as the number of bytes and messages sent or received.  
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +On EMQX Dashboard, click **Monitoring** -> **Cluster Overview** from the left navigation menu. On the **Cluster Overview** page, click the **Nodes** tab. Click the name of the node to see the details
```suggestion
On EMQX Dashboard, click **Monitoring** -> **Cluster Overview** from the left navigation menu. On the **Cluster Overview** page, click the **Nodes** tab. Click the name of the node to see the statistics details on the right.
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| client.connack      | The number of connection acknowledgment (CONNACK) messages received by clients |
```suggestion
| client.connack      | The number of connection acknowledgment (`CONNACK`) messages received by clients |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| client.disconnected | The number of client disconnections, including active and abrupt disconnection |
```suggestion
| client.disconnected | The number of client disconnections, including active and abnormal disconnections |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| authorization.allow         | The total number of client authorization passes, including getting authorization results by cache and authorization requests not matched by any rules |
```suggestion
| authorization.allow         | Total number of client authorization passes, that is, the sum of cache hits (retrieved authorization results) and matched authorization requests (those corresponding to the policy rules). |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| authorization.deny          | The total number of client authorization fails, including getting authorization results by cache and authorization requests not matched by any rules |
```suggestion
| authorization.deny          | Total number of client authorization fails, that is, the sum of cache hits (retrieved authorization results) and unmatched authorization requests (those not corresponding to any policy rules).  |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| authorization.matched.allow | The number of client authorization passes due to authorized by some rules |
```suggestion
| authorization.matched.allow | Number of client authorization passes as per the rules |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| authorization.matched.deny  | The number of client authorization fails due to being rejected by some rules |
```suggestion
| authorization.matched.deny  | The number of client authorization fails as rejected by the rules |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| authorization.nomatch       | The number of client authorization requests not matched by any rules |
```suggestion
| authorization.nomatch       | The number of client authorization requests not matching any rules |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| client.auth.anonymous       | The number of clients who log in anonymously                 |
```suggestion
| client.auth.anonymous       | The number of clients that log in anonymously                 |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| bytes.sent     | The umber of sent bytes |
```suggestion
| bytes.sent     | The number of bytes sent |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| bytes.received | The number of received bytes |
```suggestion
| bytes.received | Number of bytes received |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| messages.received               | The number of messages received from the client, which is equal to the sum of `messages.qos0.received`,` messages.qos1.received`, and `messages.qos2.received` |
```suggestion
| messages.received               | The number of messages received from the client, which is equal to the sum of `messages.qos0.received`, ` messages.qos1.received`, and `messages.qos2.received` |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| messages.sent                   | The number of messages sent to the client, which is equal to the sum of `messages.qos0.sent`,` messages.qos1.sent`, and `messages.qos2.sent` |
```suggestion
| messages.sent                   | The number of messages sent to the client, which is equal to the sum of `messages.qos0.sent`, ` messages.qos1.sent`, and `messages.qos2.sent` |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| delivery.dropped.no_local   | The number of messages that have been dropped due to the `No Local` subscription option when being sent |
```suggestion
| delivery.dropped.no_local   | The number of messages that have been dropped due to `No Local` when being sent |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| delivery.dropped.qos0_msg   | The number of messages with QoS of 0 that have been dropped because the message queue was full when being sent |
```suggestion
| delivery.dropped.qos0_msg   | Number of dropped QoS 0 messages due to a full message queue during transmission. |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| delivery.dropped.queue_full | The number of messages with a non-zero level of QoS that have been dropped because the message queue was full when being sent |
```suggestion
| delivery.dropped.queue_full | The number of dropped non-zero QoS level messages due to a full message queue during transmission. |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +| delivery.dropped.too_large  | The number of messages that have been dropped because the length exceeded the limit when being sent |
```suggestion
| delivery.dropped.too_large  | The number of dropped messages due to exceeding length limits during transmission. |
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/metrics-and-stats.md
> +You can also get the metrics and statistics through the [API Docs](https://docs.emqx.com/en/enterprise/v5.0/admin/api-docs.html). Click **Metrics** on the left navigation menu on the UI to execute th
```suggestion
You can also get the metrics and statistics through the API. On how to work with EMQX API, see  [API Docs](../admin/api.md). 
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/prometheus.md
> +- Various alarm notification means, such as using Prometheus Alertmanager.
```suggestion
- Various alarm notification options, such as using Prometheus Alertmanager.
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/prometheus.md
> +You can enable the Pushgateway server by adding the following configurations to `etc/emqx.conf`. For more information on configuration items, see [Prometheus](../configuration/prometheus.md).
```suggestion
You can enable the Pushgateway server by adding the following configurations to `etc/emqx.conf`. For more information on configuration items, see [Configuration - Prometheus](../configuration/prometheus.md).
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/topic-metrics.md
> +You can also get the topic metrics through the [API Docs](https://docs.emqx.com/en/enterprise/v5.0/admin/api-docs.html). Click **MQTT** -> **Topic Metrics** on the left navigation menu on the UI to e
```suggestion
You can also get the topic metrics through the API. On how to work with EMQX APIS, see [REST API](../admin/api.md).
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/tracer.md
> +EMQX 5.0 provides the Log Trace feature, allowing users to enable real-time debug-level log outputs for specific client IDs, topics or IP addresses. Usually, debug-level logging is not enabled in the
```suggestion
EMQX 5.0 introduces the Log Trace feature, enabling real-time debug-level log outputs for specific client IDs, topics, or IP addresses. This allows detailed debugging in production environments without affecting system performance due to excessive logs, increasing the efficiency of diagnosing and resolving EMQX issues.
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/tracer.md
> +The created trace records will be listed. You can create up to 30 traced logs. The log file size viewed in the list is the sum of the uncompressed file sizes. You can click the **Stop** button to sto
```suggestion
The created trace records will be listed. You can create up to 30 traced logs. The log file size viewed in the list is the sum of the uncompressed file sizes. You can click the **Stop** button to stop logging manually or wait until the specified end time.
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/tracer.md
> +Trace logs can generate a maximum of 512MB logs per node. If the generated log file reaches the maximum, it will stop appending logs and give an alert in the main log file. If the Dashboard download
If the Dashboard download timeout, you can find the log file directly on the server's data/trace. 这句话不是太理解 @wivwiv @Meggielqk

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/alarms.md
> +You can query and manage alarms through the [API Docs](https://docs.emqx.com/en/enterprise/v5.0/admin/api-docs.html). Click **Alarms** on the left navigation menu on the UI to execute this API reques
```suggestion
You can query and manage alarms through the API. For how to work with EMQX API, see [REST API](../admin/api.md).
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/alarms.md
> +You can query and manage alarms through the [API Docs](https://docs.emqx.com/en/enterprise/v5.0/admin/api-docs.html). Click **Alarms** on the left navigation menu on the UI to execute this API reques
```suggestion
You can query and manage alarms through the API. For how to work with EMQX API, see [REST API](../admin/api.md).
```

2023-05-06 09:23 UTC, LenaLenaPan commented on en_US/observability/log.md
> +You can also configure EMQX logging through configuration files. For example, if you want to export the warning-level logs to a file or output with a console, you can modify the configuration items u
```suggestion
You can also configure EMQX logging through configuration files. For example, if you want to export the warning-level logs to a file or output with a console, you can modify the configuration items under `log` in `emqx.conf` as shown below. The configuration takes effect after the node restarts. For more information on configuring logging with configuration files, see [Configuration - Logs](../configuration/logs.md). 
```

2023-05-06 09:23 UTC, LenaLenaPan reviewed
leave some comments

2023-05-08 03:28 UTC, Meggielqk commented on en_US/observability/tracer.md
> +Trace logs can generate a maximum of 512MB logs per node. If the generated log file reaches the maximum, it will stop appending logs and give an alert in the main log file. If the Dashboard download
我根据中文的意思改了一下英文，请见最新的commit @wivwiv @LenaLenaPan

2023-05-08 07:46 UTC, LenaLenaPan approved these changes

2023-05-08 07:47 UTC, merged