Add docs for compatibility changes between 4.4 and 5.1
emqtt/emq-docs-cn pull request #1989
Opened 2023-07-05 08:22 UTC by Meggielqk

2023-07-07 09:26 UTC, Meggielqk commented
Will the users access these incompatibility documents from the EMQX documentation site or just through the link in Change log (https://docs.emqx.com/en/enterprise/v5.1/changes/changes-5.1.html#breaking-changes)? In other words, do I need to add these documents to the dir.yaml? @id

2023-07-11 10:03 UTC, id commented on en_US/changes/breaking-changes-5.1.0.md
> +5. Pay attention to the **removal of certain features**, such as `mcast` for Cluster discovery and `EMQX Bridges` for Data integration, among others.
> and `EMQX Bridges` for Data integration

This is confusing. What does `EMQX Bridges` mean?

2023-07-11 10:03 UTC, id commented on en_US/changes/breaking-changes-5.1.0.md
> +Log files follow the same format, but the log content style has slight differences. The log format in EMQX 5.1 is more indexer-friendly.
> Log files follow the same format

vs 

> The log format in EMQX 5.1 is more indexer-friendly

I think saying "Log files follow the same format" is not exactly correct in this context.
In v5 we have the option to use either flat log file format as in 4.4, or structured json format, which is more indexer-friendly.

2023-07-11 10:03 UTC, id commented on en_US/changes/breaking-changes-5.1.0.md
> +- Tablestore, DolphinDB, Lindorm, and SAP Event Mesh are not supported.
yet

2023-07-11 10:03 UTC, id commented on en_US/changes/breaking-changes-5.1.0.md
> +- [MQTT Message Persistence](https://docs.emqx.com/en/enterprise/v4.4/backend/backend.html#mqtt-message-persistence) is not implemented in EMQX 5.0 a5.1.
```suggestion
- [MQTT Message Persistence](https://docs.emqx.com/en/enterprise/v4.4/backend/backend.html#mqtt-message-persistence) is not implemented in EMQX 5.0 and 5.1. It's planned for the later versions.
```

2023-07-11 10:03 UTC, id commented on en_US/changes/breaking-changes-5.1.0.md
> +In EMQX 4.x, various protocols can be configured through corresponding Plugins and Modules (only for the enterprise edition). However, in E5.0, we have introduced a new concept called Gateway.
```suggestion
In EMQX 4.x, various protocols can be configured through corresponding Plugins and Modules (only for the enterprise edition). However, in EMQX 5.0, we have introduced a new concept called Gateway.
```

2023-07-11 10:03 UTC, id commented on en_US/changes/breaking-changes-5.1.0.md
> +- It is **completely incompatible** from the configuration and management approaches perspective. E 5.0 has a brand new configuration format and management approach.
```suggestion
- It is **completely incompatible** from the configuration and management approaches perspective. EMQX 5.0 has a brand new configuration format and management approach.
```

2023-07-11 10:03 UTC, id commented on en_US/changes/data-integration-4.4-to-5.1-incompatibility.md
> +- Tablestore, DolphinDB, Lindorm, and SAP Event Mesh data bridges are no longer supported.
SAP Event Mesh is in the roadmap

2023-07-13 13:17 UTC, id submitted a review, later dismissed

2023-07-15 07:38 UTC, yanzhiemq submitted a review, later dismissed

2023-07-17 07:01 UTC, HJianBo commented on en_US/changes/data-integration-4.4-to-5.1-incompatibility.md
> +  <img src="./assets/mqtt-bridge-resource.png" alt="mqtt-bridge-resource" style="zoom:50%;" />
The screenshot is **MQTT Bridge* instead of **EMQX Bridge**

2023-07-17 07:02 UTC, HJianBo commented on en_US/changes/data-integration-4.4-to-5.1-incompatibility.md
> +- The previous **Rule** -> **Action** -> **Resources** process is changed to **Data Bridge** -> **Rules**.
```suggestion
- The previous **Rule** -> **Action** -> **Resources** process is changed to **Rules** -> **Data Bridge**. 
```

2023-07-17 07:10 UTC, wivwiv requested changes

2023-07-17 07:10 UTC, wivwiv commented on en_US/changes/auth-4.4-to-5.1-compatibility.md
> +- `auth_query` is changed to `query`.  `${var}`-style [placeholders](https://www.emqx.io/docs/en/v5.0/access-control/authn/authn.html#authentication-placeholders) should be used. Query should fetch a
Links to documents use relative paths, as do other links
```suggestion
- `auth_query` is changed to `query`.  `${var}`-style [placeholders](../access-control/authn/authn.html#authentication-placeholders) should be used. Query should fetch at least `password` or `password_hash` column and optionally `salt` and `is_superuser` columns.
```

2023-07-19 07:54 UTC, wivwiv approved these changes

2023-07-20 03:40 UTC, merged