Create changes-ee-5.3.md
emqtt/emq-docs-cn pull request #2118
Opened 2023-09-27 08:51 UTC by yanzhiemq

2023-09-27 09:07 UTC, id approved these changes, later dismissed

2023-09-27 09:09 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +## Enhancements
```suggestion

### Enhancements
```

2023-09-27 09:09 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +## Bug Fixes
```suggestion
### Bug Fixes
```

2023-09-27 09:09 UTC, JimMoen commented
for e5.3.0 feature:

- [#11631](https://github.com/emqx/emqx/pull/11631) Add SSO feature and integrate with LDAP.

- [#11656](https://github.com/emqx/emqx/pull/11656) Integrated the SAML 2.0 Support for SSO.

2023-09-27 09:15 UTC, yanzhiemq commented
> for e5.3.0 feature:
> 
> ```
> - [#11631](https://github.com/emqx/emqx/pull/11631) Add SSO feature and integrate with LDAP.
> 
> - [#11656](https://github.com/emqx/emqx/pull/11656) Integrated the SAML 2.0 Support for SSO.
> ```

@id I will add them in this repo directly, and @JimMoen will update them to emqx/emqx repo in next bugfix PR

2023-09-27 09:17 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +
```suggestion
- [#11631](https://github.com/emqx/emqx/pull/11631) Add SSO feature and integrate with LDAP.

- [#11656](https://github.com/emqx/emqx/pull/11656) Integrated the SAML 2.0 Support for SSO.
```

2023-09-27 09:59 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +- [#11612](https://github.com/emqx/emqx/pull/11612) During node evacuation, evacuate all disconnected sessions, not only those started with `clean_start` set to `false`.
```suggestion
```

2023-09-27 10:13 UTC, cherryxkz commented on en_US/changes/changes-ee-5.3.md
> +- [#11620](https://github.com/emqx/emqx/pull/11620) Add a new rule-engine SQL function `bytesize` to get the size of a byte-string. e.g. ``SELECT * FROM "t/#" WHERE bytesize(payload) > 10`
string. e.g. `SELECT * FROM "t/#" WHERE bytesize(payload) > 10`

2023-09-27 11:08 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +- [#11608](https://github.com/emqx/emqx/pull/11608) Integrated the LDAP bind operation as a new authenticator.
```suggestion
```

2023-09-27 11:08 UTC, yanzhiemq commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11608](https://github.com/emqx/emqx/pull/11608) 将 LDAP 绑定操作集成为新的身份验证器。
```suggestion
```

2023-09-28 02:01 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +- [#11568](https://github.com/emqx/emqx/pull/11568) Added support for defining templates for MQTT publish properties in the Republish rule action.
```suggestion
```

2023-09-28 02:01 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +- [#11612](https://github.com/emqx/emqx/pull/11612) During node evacuation, evacuate all disconnected sessions during node evacuation, not only those starting with `clean_start` set to `false`.
```suggestion
```

2023-09-28 02:01 UTC, yanzhiemq commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11612](https://github.com/emqx/emqx/pull/11612)  在节点疏散期间疏散所有断开的会话，不仅仅是那些使用 `clean_start` 设置为 `false` 开始的会话。
```suggestion
```

2023-09-28 02:01 UTC, yanzhiemq commented on zh_CN/changes/changes-ee-5.3.md
> +- [#1111682](https://github.com/emqx/emqx/pull/1111682) 修复了在文件日志处理程序上将“旋转大小”设置为`infinity`时日志记录停止的问题。
```suggestion
- [#11682](https://github.com/emqx/emqx/pull/11682) 修复了在文件日志处理程序上将“旋转大小”设置为`infinity`时日志记录停止的问题。
```

2023-09-28 02:01 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +
```suggestion
```

2023-09-28 02:01 UTC, yanzhiemq commented on zh_CN/changes/changes-ee-5.3.md
> +
```suggestion
```

2023-09-28 08:28 UTC, wivwiv requested changes

2023-09-28 08:28 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.2.md
> +- [#11487](https://github.com/emqx/emqx/pull/11487) 将 bcrypt 的工作因子 (work factor) 限制在5-10的范围内，因为较高的值会消耗太多 CPU 资源。Bcrypt 库已更新以允许并行哈希计算。
明确改动的是哪个模块。
```suggestion
- [#11487](https://github.com/emqx/emqx/pull/11487) 将认证功能中，基于 bcrypt 算法的密码加密的计算强度因子 (work factor) 限制在5-10的范围内，因为较高的值会消耗太多 CPU 资源。Bcrypt 库已更新以允许并行哈希计算。
```

2023-09-28 08:28 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.2.md
> +- [#11568](https://github.com/emqx/emqx/pull/11568) 在消息重发布规则动作中，支持设置 MQTT 5.0 发布属性与用户属性。
```suggestion
- [#11568](https://github.com/emqx/emqx/pull/11568) 在消息重发布规则动作中，支持设置 MQTT 5.0 发布属性与用户属性。目前配置接口暂未完全集成到 Dashboard，将在后续版本中提供支持。
```

2023-09-28 08:28 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11620](https://github.com/emqx/emqx/pull/11620)  添加一个新的规则引擎 SQL 函数 `bytesize` 以获取字节字符串的大小。例如：``SELECT * FROM "t/#" WHERE bytesize(payload) > 10`。
```suggestion
- [#11620](https://github.com/emqx/emqx/pull/11620)  添加一个新的规则引擎 SQL 函数 `bytesize` 以获取字节字符串的大小。例如：`SELECT * FROM "t/#" WHERE bytesize(payload) > 10`。
```

2023-09-28 08:28 UTC, wivwiv commented on en_US/changes/changes-ee-5.3.md
> +- [#11620](https://github.com/emqx/emqx/pull/11620) Added a new rule-engine SQL function `bytesize` to get the size of a byte-string. e.g. ``SELECT * FROM "t/#" WHERE bytesize(payload) > 10`.
```suggestion
- [#11620](https://github.com/emqx/emqx/pull/11620) Added a new rule-engine SQL function `bytesize` to get the size of a byte-string. e.g. `SELECT * FROM "t/#" WHERE bytesize(payload) > 10`.
```

2023-09-28 08:28 UTC, wivwiv commented on en_US/changes/changes-ee-5.3.md
> +- [#11620](https://github.com/emqx/emqx/pull/11620) Added a new rule-engine SQL function `bytesize` to get the size of a byte-string. e.g. ``SELECT * FROM "t/#" WHERE bytesize(payload) > 10`.
```suggestion
- [#11620](https://github.com/emqx/emqx/pull/11620) Added a new rule-engine SQL function `bytesize` to get the size of a byte-string. e.g. `SELECT * FROM "t/#" WHERE bytesize(payload) > 10`.
```

2023-09-28 08:49 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +- [#11620](https://github.com/emqx/emqx/pull/11620) Added a new rule-engine SQL function `bytesize` to get the size of a byte-string. e.g. ``SELECT * FROM "t/#" WHERE bytesize(payload) > 10`.
duplicated suggestion

2023-09-28 08:55 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +- [#11656](https://github.com/emqx/emqx/pull/11656) Integrated the SAML 2.0 Support for SSO.
```suggestion
- [#11656](https://github.com/emqx/emqx/pull/11656) Integrated the SAML 2.0 Support for SSO.
   Note: AuthNRequest encryption is not supported yet.
```

2023-09-28 08:55 UTC, yanzhiemq commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11656](https://github.com/emqx/emqx/pull/11656) 集成了 SAML 2.0 支持以实现单点登录（SSO）。
```suggestion
- [#11656](https://github.com/emqx/emqx/pull/11656) 集成了 SAML 2.0 支持以实现单点登录（SSO）。
   注意：暂时还不支持对AuthNRequest进行加密。
```

2023-09-28 12:34 UTC, yanzhiemq commented on zh_CN/changes/changes-ee-5.3.md
> +   注意：暂时还不支持对AuthNRequest进行加密。
```suggestion
```

2023-09-28 12:34 UTC, yanzhiemq commented on en_US/changes/changes-ee-5.3.md
> +   Note: AuthNRequest encryption is not supported yet.
```suggestion
```

2023-09-28 13:27 UTC, wivwiv approved these changes

2023-09-28 14:27 UTC, Meggielqk approved these changes

2023-09-28 14:27 UTC, merged