Update data-bridges.md ZH
emqtt/emq-docs-cn pull request #2188
Opened 2023-10-23 03:20 UTC by Meggielqk

2023-10-25 10:00 UTC, wivwiv requested changes

2023-10-25 10:00 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +数据集成通过规则引擎和数据桥接，将物联网数据无缝传输到不同的数据系统。数据桥接是用来对接 EMQX 和外部数据系统的通道，比如 MySQL、MongoDB 等数据库， 或 Kafka，RabbitMQ 等消息中间件，或 HTTP 服务器等。通过数据集成，用户可以实时地将消息从 EMQX 发送到外部数据系统。如果使用双向数据桥接，用户还可以从外部数据系统拉取数据并发送到 EMQX 的某个主题。
```suggestion
数据集成通过规则引擎和数据桥接，将物联网数据无缝传输到不同的数据系统。数据桥接是用来对接 EMQX 和外部数据系统的通道，比如 MySQL、MongoDB 等数据库，Kafka，RabbitMQ 等消息中间件或 HTTP 服务等。通过数据集成，用户可以实时地将消息从 EMQX 发送到外部数据系统。如果使用双向数据桥接，用户还可以从外部数据系统拉取数据并发送到 EMQX 的某个主题。
```

2023-10-25 10:00 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +EMQX 数据集成是一个开箱即用的功能，在可视化界面上简单配置，无需编写代码即可将物联网数据传输到外部数据系统。作为一个 MQTT 消息平台，EMQX 通过 MQTT 协议接收来自物联网设备的数据。借助内置的规则引擎，接收到的数据会被规则引擎中配置的规则进行处理。规则将触发一个动作，将经过处理的数据通过配置的数据桥接传递到外部数据系统。您可以在 EMQX Dashboard上轻松创建规则、将动作
简化描述，弱化动作概念
```suggestion
EMQX 数据集成是一个开箱即用的功能，在可视化界面上简单配置，无需编写代码即可将物联网数据传输到外部数据系统。作为一个 MQTT 消息平台，EMQX 通过 MQTT 协议接收来自物联网设备的数据。借助内置的规则引擎，接收到的数据会通过用户配置的规则进行处理。处理完成后，规则将通过配置的数据桥接，将处理后的数据发送到外部数据系统。您可以在 EMQX Dashboard 上轻松创建规则、并添加数据桥接。
```

2023-10-25 10:00 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +强大的规则引擎是基于 MQTT 的数据处理和分发的核心组件。在物联网数据被传输到外部数据系统之前，数据将经过规则引擎，按照规则进行实时数据提取、过滤、丰富和格式转换。当规则添加了定义数据处理方式的动作时，EMQX 将输出处理结果到配置的数据桥接。
```suggestion
规则引擎是内置的基于 SQL 的数据处理和分发核心组件。来自客户端的物联网数据将经过规则引擎，进行实时的提取、过滤、丰富和格式转换处理，并将输出到指定的数据桥接中。
```

2023-10-25 10:08 UTC, wivwiv requested changes

2023-10-25 10:08 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +来自各种物联网设备和系统的数据源具有各种数据类型和格式。为了获取所需的数据，规则中使用基于 SQL 的语法进行数据提取、过滤、丰富和转换。有关基于 SQL 的规则的详细信息，请参阅 [SQL 语法与示列](./rule-sql-syntax.md)。
```suggestion
来自各种物联网设备和系统的数据源具有不同的数据类型和格式。规则 SQL 内置了丰富的函数，包括字符处理、数据类型转换函数、压缩/解压缩函数，可以灵活的进行复杂数据处理。有关基于 SQL 的规则的详细信息，请参阅 [SQL 语法与示列](./rule-sql-syntax.md)。
```

2023-10-25 10:08 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +## 数据集成运行
```suggestion
## 数据集成状态与指标
```

2023-10-25 11:43 UTC, Meggielqk commented on zh_CN/data-integration/data-bridges.md
> +强大的规则引擎是基于 MQTT 的数据处理和分发的核心组件。在物联网数据被传输到外部数据系统之前，数据将经过规则引擎，按照规则进行实时数据提取、过滤、丰富和格式转换。当规则添加了定义数据处理方式的动作时，EMQX 将输出处理结果到配置的数据桥接。
“来自客户端的物联网数据将经过规则引擎，进行实时的提取、过滤、丰富和格式转换处理，并将输出到指定的数据桥接中。” 这句话的意思是不是指“数据”经过规则引擎处理，并“输出”到数据桥接“？是不是把”将“去掉就可以了？

2023-10-26 06:34 UTC, wivwiv approved these changes

2023-10-26 06:34 UTC, merged