docs: gbt32960 doc
emqtt/emq-docs-cn pull request #2214
Opened 2023-11-13 08:23 UTC by lafirest

2023-12-11 10:01 UTC, wivwiv requested changes

2023-12-11 10:01 UTC, wivwiv commented on en_US/gateway/gbt32960.md
> +## Configure Authentication
Stomp? 需要确认支持的认证器 @lafirest

2023-12-20 09:34 UTC, Meggielqk commented on en_US/gateway/gbt32960.md
> +# GBT/32960 Gateway
```suggestion
# GB/T 32960 Gateway
```

2023-12-22 08:25 UTC, wivwiv approved these changes

2023-12-22 08:25 UTC, merged