Update changes-ee-5.3.md for e5.3.2
emqtt/emq-docs-cn pull request #2238
Opened 2023-11-30 06:28 UTC by yanzhiemq

2023-11-30 07:44 UTC, id approved these changes, later dismissed

2023-11-30 08:09 UTC, hjianbo submitted a review, later dismissed

2023-11-30 08:35 UTC, zmstone commented on en_US/changes/changes-ee-5.3.md
> +- [#11785](https://github.com/emqx/emqx/pull/11785) Allow viewer to change their own passwords, viewer can't change other's password.
```suggestion
- [#11785](https://github.com/emqx/emqx/pull/11785) Allow `viewer` dashboard role to change their passwords.
```

2023-11-30 09:28 UTC, wivwiv requested changes

2023-11-30 09:28 UTC, wivwiv commented on en_US/changes/changes-ee-5.3.md
> +  Avoid loading EMQX application code in `nodetool` script unless necessary.
This is for internal developers, not for users
```suggestion
```

2023-11-30 10:06 UTC, wivwiv requested changes

2023-11-30 10:06 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11785](https://github.com/emqx/emqx/pull/11785) 允许拥有“查看者”角色的用户更改自己的密码。然而，拥有“查看者”角色的用户没有权限更改其他用户的密码。
```suggestion
- [#11785](https://github.com/emqx/emqx/pull/11785) 拥有“查看者”角色的用户具有更改自己密码的权限，但无权更改其他用户密码。
```

2023-11-30 10:06 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11790](https://github.com/emqx/emqx/pull/11790) 为配置在 Redis 授权数据源中的 Redis 命令添加了验证功能。此外，此次改进优化了认证和授权过程中 Redis 命令的解析。现在的解析符合 `redis-cli` 兼容性标准，并支持引号参数。
```suggestion
- [#11790](https://github.com/emqx/emqx/pull/11790) 为 Redis 授权数据源中的 Redis 命令添加了验证功能。此外，此次改进优化了认证和授权过程中 Redis 命令的解析，现在的解析符合 `redis-cli` 兼容性标准，并支持引号参数。
```

2023-11-30 10:06 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11541](https://github.com/emqx/emqx/pull/11541) 通过引入更多的互动方式，增强了 EMQX 的文件传输能力。现在，客户端可以将文件传输命令发送到 `$file-async/...` 主题，而不是 `$file/...`。命令执行结果将作为消息发送到 `$file-response/{clientId}` 主题。 这一增强在某些情况下简化了文件
```suggestion
- [#11541](https://github.com/emqx/emqx/pull/11541) 文件传输能力得到了增强。现在，客户端可以使用异步方式，通过 `$file-async/...` 主题进行文件传输，并通过 `$file-response/{clientId}` 主题订阅命令执行结果。这一改进简化了文件传输功能的使用，尤其适用于 MQTT v3.1/v3.1.1 或使用了 MQTT 桥接的客户端。 更多详情请参阅 [EIP-0021](https://github.com/emqx/eip)。
```

2023-11-30 10:06 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11762](https://github.com/emqx/emqx/pull/11762) 修复了 EMQX 中 `built_in_database` 授权数据源的一个问题。通过这次修复，现在在销毁授权数据源时，所有访问控制列表（ACL）记录都会被彻底移除。这解决了以前的问题，即数据库中残留的记录可能在重新创建授权数据源时导致问题。
```suggestion
- [#11762](https://github.com/emqx/emqx/pull/11762) 修复了 EMQX 中 `built_in_database` 授权数据源的一个问题。通过这次修复，现在在删除数据源时，所有 ACL 记录都会被彻底移除。这解决了数据库残留的记录在重新创建授权数据源时仍然存在的问题。
```

2023-11-30 10:06 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11771](https://github.com/emqx/emqx/pull/11771) 修复了通过 API/Dashboard 进行身份验证管理时 Bcrypt 盐轮次的验证问题。
```suggestion
- [#11771](https://github.com/emqx/emqx/pull/11771) 修复了通过 API/Dashboard 进行身份验证管理时 Bcrypt 盐轮次(salt rounds)的验证问题。
```

2023-11-30 10:06 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11731](https://github.com/emqx/emqx/pull/11731) 将文件传输功能配置添加到了热配置模式。
```suggestion
- [#11731](https://github.com/emqx/emqx/pull/11731) 为文件传输功能添加了热配置支持。
```

2023-11-30 10:06 UTC, wivwiv commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11754](https://github.com/emqx/emqx/pull/11754) 改进了 EMQX 中针对 Postgres 桥接的日志格式化功能。这个改进针对驱动程序返回的错误消息中的 Unicode 字符进行了处理。
```suggestion
- [#11754](https://github.com/emqx/emqx/pull/11754) 改进了  Postgres 桥接的日志格式化功能，针对驱动程序返回的错误消息中的 Unicode 字符进行了处理。
```

2023-11-30 10:34 UTC, yanzhiemq commented on zh_CN/changes/changes-ee-5.3.md
> +- [#11754](https://github.com/emqx/emqx/pull/11754) 改进了  Postgres 桥接的日志格式化功能，针对驱动程序返回的错误消息中的 Unicode 字符进行了处理。
```suggestion
- [#11754](https://github.com/emqx/emqx/pull/11754) 改进了 Postgres 桥接的日志格式化功能，针对驱动程序返回的错误消息中的 Unicode 字符进行了处理。
```

2023-11-30 14:06 UTC, zmstone approved these changes

2023-12-01 03:22 UTC, wivwiv approved these changes

2023-12-01 03:33 UTC, merged