Refactor Data Integration for Bridge-V2
emqtt/emq-docs-cn pull request #2360
Opened 2024-02-07 09:08 UTC by Meggielqk

2024-02-07 09:09 UTC, Meggielqk commented
Still in draft state and more data integration pages will be updated later...

2024-02-09 13:20 UTC, zmstone commented on en_US/data-integration/data-bridge-cassa.md
> +11. On the **Create Rule** page, verify the configured information and click the **Create** button to generate the rule. The rule you created is shown in the rule list and the **status** should be co
markdown allows you to use `1. ` for all bullets, and it will be rendered as 1 ~ N.

2024-02-09 13:20 UTC, zmstone commented on en_US/data-integration/data-bridge-cassa.md
> +11. On the **Create Rule** page, verify the configured information and click the **Create** button to generate the rule. The rule you created is shown in the rule list and the **status** should be co
so there is no need to manually keeping the order

2024-03-21 06:28 UTC, wivwiv requested changes

2024-03-21 06:28 UTC, wivwiv commented on en_US/data-integration/data-bridge-mysql.md
> +The following steps assume that you run both EMQX and TDengine on the local machine. If you have TDengine and EMQX running remotely, adjust the settings accordingly.
```suggestion
The following steps assume that you run both EMQX and MySQL on the local machine. If you have MySQL and EMQX running remotely, adjust the settings accordingly.
```

2024-03-25 01:43 UTC, wivwiv approved these changes

2024-03-25 01:43 UTC, merged