Correct links and textual issues
emqtt/emq-docs-cn pull request #2385
Opened 2024-03-07 09:26 UTC by Meggielqk

Quick fix for part of the issues listed on https://emqx.atlassian.net/wiki/spaces/QA/pages/796723223/Record+of+5.x+document+testing+issues

2024-03-21 03:36 UTC, wivwiv requested changes

2024-03-21 03:36 UTC, wivwiv commented on en_US/access-control/authz/ldap.md
> -   - **Publish_attribute**: Indicates which attribute is used to represent the allowed topics list of the `publish`.
为什么这几个要删除？

2024-03-21 03:36 UTC, wivwiv commented on zh_CN/access-control/authn/jwt.md
> +## <!--通过配置文件配置-->
```suggestion
<!--## 通过配置文件配置-->
```

2024-03-21 03:36 UTC, wivwiv commented on zh_CN/configuration/configuration.md
> +EMQX 支持通过修改配置文件或使用环境变量来设置 EMQX，本章节将介绍 EMQX 配置文件基本信息，配置项以及详细的介绍请参考[配置手册](https://www.emqx.io/docs/zh/v${EE_VERSION}/hocon/)。
```suggestion
EMQX 支持通过修改配置文件或使用环境变量来设置 EMQX，本章节将介绍 EMQX 配置文件基本信息，配置项以及详细的介绍请参考[配置手册]
(https://docs.emqx.com/zh/enterprise/v${EE_VERSION}/hocon/)。
```

2024-03-21 03:39 UTC, wivwiv commented
另外，为避免冲突，内容中的版本替换使用的是 `@x@` 语法，需要把所有用了 `${x}` 的语法改掉：

```
https://www.emqx.io/docs/zh/v${EE_VERSION}/hocon/

改为

https://www.emqx.io/docs/zh/v@EE_VERSION@/hocon/
```

2024-03-22 07:10 UTC, Meggielqk commented on en_US/access-control/authz/ldap.md
> -   - **Publish_attribute**: Indicates which attribute is used to represent the allowed topics list of the `publish`.
QA 说 Dashboard上没有这几项。我看了 5.6 测试版的 Dashboard，确实没有。

2024-03-25 01:46 UTC, wivwiv approved these changes, later dismissed

2024-03-25 01:54 UTC, wivwiv approved these changes

2024-03-25 01:54 UTC, merged