Log throttling doc
emqtt/emq-docs-cn pull request #2392
Opened 2024-03-13 14:12 UTC by SergeTupchiy

2024-03-14 09:44 UTC, Meggielqk commented
Dashboard screenshots need to be added later when the UI is ready.

2024-03-15 06:43 UTC, wivwiv requested changes

2024-03-15 06:43 UTC, wivwiv commented on zh_CN/observability/log.md
> +## 日志限制
```suggestion
## 日志限流
```

the same as below.

2024-03-15 06:43 UTC, wivwiv commented on zh_CN/observability/log.md
> +日志限制功能可以通过限制指定时间窗口内重复事件的记录来减少日志溢出的风险。通过仅记录第一个事件并在此窗口内抑制后续相同事件的记录，日志管理能够变得更加高效，同时不牺牲可观测性。
```suggestion
日志限流功能可以通过限制指定时间窗口内重复事件的记录来减少日志溢出的风险。通过仅记录第一个事件并在此窗口内抑制后续相同事件的记录，日志管理能够变得更加高效，同时不牺牲可观测性。
```

2024-03-20 14:32 UTC, zmstone submitted a review, later dismissed

2024-03-20 15:46 UTC, zmstone approved these changes

2024-03-20 16:26 UTC, wivwiv approved these changes

2024-03-20 16:36 UTC, merged