feat(alias extraction): Add alias-extraction.md
emqtt/emq-docs-cn pull request #2432
Opened 2024-04-22 10:12 UTC by Meggielqk

2024-04-25 20:32 UTC, zmstone submitted a review, later dismissed

2024-05-14 10:27 UTC, zmstone commented on en_US/configuration/configuration.md
> +configurations or EMQX to perform string operations dynamically.
or EMQX -> for EMQX

2024-05-16 08:03 UTC, wivwiv commented on en_US/client-attributes/client-attributes.md
>  - `ip_address`: The source IP of the client
@zmstone It looks like ip_address and port are not supported. 
```bash
2024-05-16T07:58:50.980120+00:00 [warning] msg: client_attr_initialization_failed, peername: 127.0.0.1:57746, reason: #{reason => var_unbound,var_name => "ip_address"}
2024-05-16T07:58:50.983633+00:00 [warning] msg: client_attr_initialization_failed, peername: 127.0.0.1:57746, reason: #{reason => var_unbound,var_name => "port"}
```

2024-05-16 14:26 UTC, zmstone commented on en_US/client-attributes/client-attributes.md
>  - `ip_address`: The source IP of the client
my bad, it's a part of the connection property, but not client property.
we can delete this from the docs for now?

2024-05-17 07:31 UTC, wivwiv requested changes

2024-05-17 07:31 UTC, wivwiv commented on en_US/access-control/authn/http.md
> +`client_attrs` 是可选的
typo

2024-05-17 07:31 UTC, wivwiv commented on en_US/client-attributes/client-attributes.md
>  - `ip_address`: The source IP of the client
@Meggielqk please delete them

2024-05-17 07:31 UTC, wivwiv commented on zh_CN/access-control/authz/authz.md
> +- `${client_attrs.NAME}`: 某一个客户端属性，`NAME` 替换成 `mqtt.client_attrs_init` 规则提取的某一个字段名称。
```suggestion
- `${client_attrs.NAME}`: 某一个客户端属性，`NAME` 替换成 [客户端属性](../../client_attributes/client_attributes.md)设置的属性名称。
```

2024-05-21 17:52 UTC, zmstone approved these changes

2024-05-23 09:42 UTC, wivwiv approved these changes

2024-05-23 09:43 UTC, merged