docs(zone): expose zone
emqtt/emq-docs-cn pull request #2437
Opened 2024-04-27 06:48 UTC by zmstone

2024-04-28 07:01 UTC, wivwiv commented on en_US/configuration/configuration.md
> +}
Add a configuration that shows how to bind a listener to a created zone.

2024-04-30 02:10 UTC, wivwiv approved these changes, later dismissed

2024-04-30 09:58 UTC, zmstone commented on zh_CN/configuration/configuration.md
> +### 区域覆盖
```suggestion
### Zone 覆盖 
```

2024-04-30 09:59 UTC, zmstone commented on zh_CN/configuration/configuration.md
> +EMQX 中的区域是一种配置分组的概念。可以通过将 `zone` 字段设置为所需区域的名称，将区域与监听器关联。与某个区域关联的监听器连接的 MQTT 客户端将继承该区域的配置，这些配置可能会覆盖全局设置。
```suggestion
EMQX 中的区域是一种配置分组的概念。可以通过将监听器的 `zone` 字段设置为所需区域的名称，将区域与监听器关联。与某个区域关联的监听器连接的 MQTT 客户端将继承该区域的配置，这些配置可能会覆盖全局设置。
```

2024-05-08 07:49 UTC, wivwiv requested changes

2024-05-08 07:49 UTC, wivwiv commented on en_US/configuration/configuration.md
> +
```suggestion
In any listener, set the zone field to associate with a zone that has been created.

```bash
listeners.tcp.default {
   bind = 1883
   zone = my_zone1
   ...
}
```

```

2024-05-08 15:21 UTC, merged