feat: plugin config write guide
emqtt/emq-docs-cn pull request #2444
Opened 2024-05-09 01:11 UTC by JimMoen

2024-05-09 08:02 UTC, wivwiv requested changes

2024-05-09 08:02 UTC, wivwiv commented on zh_CN/extensions/plugins.md
> +#### 为插件编写 Config Schema （可选）
```suggestion
#### 为插件编写 Config Schema （可选）

{% emqxce %}
:::tip
EMQX 企业版功能。EMQX 企业版可以为您带来更全面的关键业务场景覆盖、更丰富的数据集成支持，更高的生产级可靠性保证以及 24/7 的全球技术支持，欢迎[免费试用](https://www.emqx.com/zh/try?product=enterprise)。
:::
{% endemqxce %}
```

2024-05-09 08:02 UTC, wivwiv commented on en_US/extensions/plugins.md
> +#### Write Config Schema for the plugin (Optional)
```suggestion
#### Write Config Schema for the plugin (Optional)

{% emqxce %}
:::tip
EMQX Enterprise Edition features. EMQX Enterprise Edition provides comprehensive coverage of key business scenarios, rich data integration, product-level reliability, and 24/7 global technical support. Experience the benefits of this [enterprise-ready MQTT messaging platform](https://www.emqx.com/en/try?product=enterprise) today.
:::
{% endemqxce %}
```

2024-05-10 16:20 UTC, zmstone requested changes, later dismissed
please also add:
1. Where should the initial config (before EMQX boot) be provided (maybe in the priv dir)
2. Where are the updated config file stored, (explain overwrite, and the bak files too?)

2024-05-10 16:20 UTC, zmstone commented on en_US/extensions/plugins.md
> +{% endemqxce %}
this part is repeated.

2024-05-10 16:20 UTC, zmstone commented on en_US/extensions/plugins.md
> +Furthermore, you can declare UI in this schema, allowing the EMQX Dashboard to render configuration forms for ease of use.
The initial load of the plugin config seems to be missed in the feature implementation ?

```suggestion
Starting with version 5.7, the EMQX plugin framework pre-loads JSON or HOCON format configuration file for each plugin before startup and validates them against an optional schema, if provided. The configuration schema should be described using an Avro schema, located in the file priv/plugin_name.avsc. Additionally, configurations can be updated at runtime by utilizing the management API with the request PUT /plugins/:name/config.

For the EMQX Enterprise edition, users have the option to include $ui metadata within the Avro schema objects. This metadata aids in generating a configuration management page on the dashboard, enhancing user interaction and ease of management.
```

2024-05-10 16:20 UTC, zmstone commented on en_US/extensions/plugins.md
> +You can find two example files in the project directory: `priv/config_schmea.avsc.example`, `priv/config_i18n.json.example`.
```suggestion
You can find two example files in the [template project](https://github.com/emqx/emqx-plugin-template) directory: `priv/config_schmea.avsc.example`, `priv/config_i18n.json.example`.
```

2024-05-11 07:37 UTC, zmstone commented on en_US/extensions/plugins.md
> +EMQX Enterprise version 5.7.0 introduced Avro Schema for plugins, enhancing the ability to update plugin configurations dynamically during runtime. This feature also allows for the declaration of a u
Avro schema is available for opensource edition, the UI for configuration management is provided in Enterprise only.

```suggestion
EMQX version 5.7.0 introduced REST API for plugin configuration management and Avro Schema for configuration validation, enhancing the ability to update plugin configurations dynamically during runtime.
For Enterprise edition, it also allows the declaration of a user interface in the schema, enabling the EMQX Dashboard to dynamically generate configuration forms for easier management.
```

2024-05-16 09:09 UTC, zhongwencool commented on en_US/extensions/plugins.md
> +│   └── config_schmea.avsc.example
typo: schema

2024-05-17 08:46 UTC, wivwiv requested changes

2024-05-17 08:46 UTC, wivwiv commented on zh_CN/extensions/plugins.md
> +我们在 EMQX 企业版 5.7.0 中为插件引入了 Avro Schema 以提供在运行时更新插件配置的能力，并且可以在该 Schema 中提供 UI 声明，从而可以在 EMQX Dashboard 中渲染配置表单以便使用。
```suggestion
我们在 EMQX v5.7.0 中引入了用于插件配置管理的 REST API 和用于配置验证的 Avro Schema，增强了在运行期间动态更新插件配置的能力。
对于企业版，它还允许在 Schema 中声明配置界面，从而使 EMQX Dashboard 能够动态生成配置表单，方便插件的配置和管理。
```

2024-05-24 02:23 UTC, wivwiv submitted a review, later dismissed

2024-05-24 02:27 UTC, wivwiv approved these changes

2024-05-24 06:40 UTC, merged