Add release note of 5.7.1
emqtt/emq-docs-cn pull request #2552
Opened 2024-06-25 01:36 UTC by yanzhiemq

2024-06-25 07:02 UTC, wivwiv requested changes

2024-06-25 07:02 UTC, wivwiv commented on en_US/changes/changes-ee-v5.md
> +- [#13180](https://github.com/emqx/emqx/pull/13180) Improve client message handling performance when running on OTP 26.
```suggestion
- [#13180](https://github.com/emqx/emqx/pull/13180) Improve client message handling performance when running on OTP 26.  Increased message throughput by 10% in fan-in mode.
```

2024-06-26 03:12 UTC, wivwiv requested changes

2024-06-26 03:12 UTC, wivwiv commented on en_US/changes/changes-ee-v5.md
> +  - Prefix no more than 19 bytes: The prefix is preserved, and the client ID is hashed into a 4-byte space capping the length within 23 bytes.
@zmstone please confirm
```suggestion
  - Prefix no more than 19 bytes: The prefix is preserved, and the remainder of the client ID is hashed into a 4-byte space capping the length within 23 bytes.
```

2024-06-26 08:33 UTC, zmstone commented on en_US/changes/changes-ee-v5.md
> +  - Prefix no more than 19 bytes: The prefix is preserved, and the client ID is hashed into a 4-byte space capping the length within 23 bytes.
this is correct.

2024-06-26 08:33 UTC, zmstone submitted a review, later dismissed

2024-06-26 09:09 UTC, zmstone commented on en_US/changes/changes-ce-v5.md
> +
this part is only relevant to enterprise because schema registry is an ee only feature.
```suggestion

```

2024-06-26 10:05 UTC, Meggielqk commented on zh_CN/changes/changes-ee-v5.md
> +- [#13273](https://github.com/emqx/emqx/pull/13273) 修复并改进了在以下几个配置中对URI的处理，具体包括：
```suggestion
- [#13273](https://github.com/emqx/emqx/pull/13273) 修复并改进了在以下几个配置中对 URI 的处理，具体包括：
```

2024-06-26 10:06 UTC, Meggielqk commented on zh_CN/changes/changes-ee-v5.md
> +  - 认证和授权配置：纠正了先前的错误，之前错误地拒绝了没有路径的有效 URI，如 `https://example.com?q=x`。这些URI现在被正确识别为有效。
```suggestion
  - 认证和授权配置：纠正了先前的错误，之前错误地拒绝了没有路径的有效 URI，如 `https://example.com?q=x`。这些 URI 现在被正确识别为有效。
```

2024-06-26 11:05 UTC, yanzhiemq commented on en_US/changes/changes-ee-v5.md
> +- [#12983](https://github.com/emqx/emqx/pull/12983) Add new rule engine event `$events/client_check_authn_complete` for authentication completion event.
this changelog is not added to Chinese edition yet @Meggielqk

2024-06-26 13:36 UTC, Meggielqk commented on zh_CN/changes/changes-ee-v5.md
> +  此选项用于不支持预处理语句会话功能的端点，例如 PGBouncer 和 Transaction 模式下的 Supabase。
```suggestion
  此选项适用于不支持像预处理语句这样的会话功能的端点，例如 PGBouncer 和 Transaction 模式下的 Supabase。
```

2024-06-26 14:39 UTC, wivwiv approved these changes

2024-06-26 14:40 UTC, merged