fix exproto.proto file url
emqtt/emq-docs-cn pull request #880
Opened 2021-10-22 05:45 UTC by wivwiv

2021-10-22 05:58 UTC, Swilder-M submitted a review, later dismissed

2021-12-27 11:06 UTC, HJianBo requested changes

2021-12-27 11:06 UTC, HJianBo commented on zh_CN/modules/exproto.md
> +详情参见：[exproto.proto](https://github.com/emqx/emqx/blob/cd22f54f08/apps/emqx_gateway/src/exproto/protos/exproto.proto)，例如接口的定义有：
```suggestion
详情参见：[exproto.proto](https://github.com/emqx/emqx/blob/main-v4.3/apps/emqx_exproto/priv/protos/exproto.proto)，例如接口的定义有：
```

2021-12-27 11:07 UTC, HJianBo commented on zh_CN/modules/exproto.md
> +详情参见：[exproto.proto](https://github.com/emqx/emqx/blob/cd22f54f08/apps/emqx_gateway/src/exproto/protos/exproto.proto)，例如接口的定义有：
We should use the proto file corresponding to v4.3, not the 5

2022-02-28 03:44 UTC, HJianBo approved these changes

2022-02-28 03:44 UTC, merged