docs: translate three files for release-4.4
emqtt/emq-docs-cn pull request #956
Opened 2021-12-18 03:07 UTC by rnhx

Signed-off-by: rnhx <787016356@qq.com>

2021-12-20 01:44 UTC, lafirest requested changes

2021-12-20 01:44 UTC, lafirest commented on en_US/modules/slow_subscribers_statistics.md
> +        1.  [Delay calculation method](#org693a7e9)
Delay -> latency, and all others

2021-12-20 01:44 UTC, lafirest commented on en_US/modules/slow_subscribers_statistics.md
> +
zh_CN -> en_US

2021-12-20 01:44 UTC, lafirest commented on en_US/modules/slow_subscribers_statistics.md
> +Since QoS1 and QoS2 messages may fail to complete the transmission process due to various reasons at the same time, this function will also try to add subscribers to the ranking according to the time
timeout -> expire

2021-12-20 01:44 UTC, lafirest commented on en_US/modules/slow_subscribers_statistics.md
> +![image](D:/emqx/emqx-docs/zh_CN/modules/assets/slow_subscribers_statistics_2.png)
zh_CN -> en_US

2021-12-21 07:30 UTC, tigercl approved these changes

2021-12-21 07:34 UTC, merged